import subprocess
import sys

def main(argv):
  if len(argv) < 1:
    print "Usage: make_utilization_box_whiskers.py event_log_filename"
    sys.exit(1)
  
  event_log_filename = argv[0]

  # This script assumes that the utilization files have already been generated by
  # parse_event_logs.py.
  output_prefix = "%s_utilization_box_whiskers" % event_log_filename
  output_plot_filename = "%s.gp" % output_prefix
  print "Writing output plot to %s" % output_plot_filename
  output_plot_file = open(output_plot_filename, "w")
  for line in open("plot_utilization_box_whiskers_base.gp"):
    output_plot_file.write(line.replace("__PREFIX__", event_log_filename))
  output_plot_file.close()

  # Make the plot.
  subprocess.check_call("gnuplot %s" % output_plot_filename, shell=True)
  subprocess.check_call("open %s.pdf" % output_prefix, shell=True)


if __name__ == "__main__":
  main(sys.argv[1:])
